yamlApplicationConfig:
  kafka:
    clusters:
      - name: yaml
        bootstrapServers: local-confluent-kafka-cp-kafka-headless:9092
  auth:
    type: disabled
  management:
    health:
      ldap:
        enabled: false